
-- Run this in Supabase SQL Editor.
-- Then add SUPABASE_URL and SUPABASE_KEY to Streamlit Secrets.
create table if not exists transactions (
  id bigint generated by default as identity primary key,
  txn_date date not null,
  description text not null,
  amount numeric not null,
  direction text not null,
  category text not null,
  class text not null,
  source text,
  fingerprint text unique
);

create table if not exists rules (
  id bigint generated by default as identity primary key,
  pattern text unique not null,
  category text not null,
  class text not null,
  created_at timestamptz default now()
);

create table if not exists loans (
  id bigint generated by default as identity primary key,
  name text not null,
  lender text,
  principal numeric not null,
  annual_rate numeric not null,
  emi numeric not null,
  start_date date not null,
  tenure_months integer not null,
  extra_payment numeric default 0
);

-- IMPORTANT:
-- This v3 app uses a server-side service key in Streamlit Secrets for
-- simplicity. Never put that key in GitHub or client-side code.
-- For a multi-user production system, add Supabase Auth + Row Level Security
-- and a per-user user_id column to every table.


-- v4 runway extensions: recurring income sources and realized swing-trading P/L
create table if not exists income_sources (
  id bigint generated by default as identity primary key,
  name text not null,
  monthly_amount numeric not null,
  start_date date not null,
  end_date date,
  annual_growth_pct numeric default 0,
  months_per_year integer default 12,
  active boolean default true
);

create table if not exists trading_results (
  id bigint generated by default as identity primary key,
  trade_date date not null,
  realized_pnl numeric not null,
  notes text
);

-- This app uses the server-side Supabase secret key from Streamlit Secrets.
-- Keep that key out of GitHub and client-side code.
